name: Game Day Live Updates

on:
  schedule:
    # Run every 30 minutes during game hours (1 PM - 11 PM EST)
    # Times in UTC: 18:00, 18:30, 19:00... 04:00
    - cron: '0,30 18-23 * * *'  # 6 PM - 11:59 PM UTC (1 PM - 6:59 PM EST)
    - cron: '0,30 0-4 * * *'    # 12:00 AM - 4:30 AM UTC (7 PM - 11:30 PM EST)
  
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  live-updates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check for game updates
      run: |
        python fetch_mlb_data.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Update dashboard if games changed
      run: |
        # Only regenerate if database was updated
        if git diff --name-only | grep -q "mlb_data.db"; then
          echo "Database updated, regenerating dashboard..."
          python generate_static_site.py
        else
          echo "No database changes, skipping dashboard regeneration"
        fi
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Commit live updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "MLB Live Update Bot"
        
        # Add changes if any
        git add .
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No live updates needed"
        else
          git commit -m "📺 Live update: $(date +'%Y-%m-%d %H:%M UTC')"
          git push origin main
          echo "Live updates pushed successfully"
        fi
