name: Daily MLB Predictions Update

on:
  schedule:
    # Run daily at 6 AM EST (11:00 UTC) - before games start
    - cron: '0 11 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-predictions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Fetch latest MLB data
      run: |
        python fetch_mlb_data.py
      env:
        # MLB Stats API is free and doesn't require API key
        PYTHONIOENCODING: utf-8
    
    - name: Generate static site
      run: |
        python generate_static_site.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        
        # Add all changes
        git add .
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-update MLB predictions for $(date +'%Y-%m-%d %H:%M UTC')"
          git push origin main
          echo "Changes committed and pushed successfully"
        fi
  # GitHub Pages deployment happens automatically when pushing to main
  # since we're using the 'Deploy from a branch' setting
